### ISSUE TITLE
Update codecov action to v4

### ISSUE THREAD

**Issue by coretl** [DiamondLightSource/python-copier-template#46]
This will require an API key, which is stored as `secrets.CODECOV_TOKEN` in the `DiamondLightSource` org.

Should just be a case of changing to:
```yaml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: ${{ inputs.python-version }}/${{ inputs.runs-on }}
          files: cov.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}        
```

Add docs that say if the repo is hosted in another org you need to visit `https://app.codecov.io/account/gh/<org_name>/org-upload-token` to generate a token for your org, and store it in `https://github.com/organizations/<org_name>/settings/secrets/actions`
